# HKI Room Template Sensors
sensor:

  - platform: template
    sensors:
      # Kitchen
      current_kitchen_lights_on:
        friendly_name: All Kitchen Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.kitchen_lights','entity_id'))|selectattr('state','eq','on')|list|count }}
      # Living Room
      current_living_room_lights_on:
        friendly_name: All Living Room Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.living_room_lights','entity_id'))|selectattr('state','eq','on')|list|count }}
      # Living Room
      current_hall_lights_on:
        friendly_name: All Living Room Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.hall_lights','entity_id'))|selectattr('state','eq','on')|list|count }}
      # Bathroom
      current_bathroom_lights_on:
        friendly_name: All Living Room Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.bathroom_lights','entity_id'))|selectattr('state','eq','on')|list|count }}

      # Landing
      current_landing_lights_on:
        friendly_name: All Living Room Lights Currently On
        value_template: >-
          {{ states|selectattr('entity_id','in',state_attr('group.landing_lights','entity_id'))|selectattr('state','eq','on')|list|count }}


# HKI Room Automations
automation:

  - alias: 'group state change 8'
    id: 'State changed 8'
    trigger:
      - platform: event
        event_type: state_changed
    condition: 
      - condition: template
        value_template: "{{ trigger.event.data.new_state is defined }}"

      # Kitchen Lights
      - condition: template
        value_template: >
          {{ trigger.event.data.entity_id in state_attr('group.kitchen_lights','entity_id') }}

      # Living Room Lights
      - condition: template
        value_template: >
          {{ trigger.event.data.entity_id in state_attr('group.living_room_lights','entity_id') }}

      # Hall Lights
      - condition: template
        value_template: >
          {{ trigger.event.data.entity_id in state_attr('group.hall_lights','entity_id') }}

      # Bathroom
      - condition: template
        value_template: >
          {{ trigger.event.data.entity_id in state_attr('group.bathroom_lights','entity_id') }}

      # Landing
      - condition: template
        value_template: >
          {{ trigger.event.data.entity_id in state_attr('group.landing_lights','entity_id') }}

    action:
      service: homeassistant.update_entity
      entity_id: 
        - sensor.current_kitchen_lights_on
        - sensor.current_living_room_lights_on
        - sensor.current_hall_lights_on
        - sensor.current_bathroom_lights_on
        - sensor.current_landing_lights_on
