# UnRAID Server Montitoring for Dwains-Theme
## Version 0.3 by noodlemctwoodle

# UnRAID Sensors v1.2

## UnRAID Version Sensor URLs
### Stable URL: https://s3.amazonaws.com/dnld.lime-technology.com/stable/unRAIDServer.plg
### Beta URL: https://s3.amazonaws.com/dnld.lime-technology.com/next/unRAIDServer.plg

camera:
  - platform: generic
    name: cpu_load
    still_image_url: http://10.0.10.12:3000/render/d-solo/000130-PUB-falconexe/unraid-dashboard?orgId=1&refresh=1m&panelId=126&width=700&height=200
    username: !secret grafanaUser
    password: !secret grafanaPass

  - platform: generic
    name: docker_ram
    still_image_url: http://10.0.10.12:3000/render/d-solo/000130-PUB-falconexe/unraid-dashboard?orgId=1&refresh=15m&panelId=114&width=1000&height=500
    username: !secret grafanaUser
    password: !secret grafanaPass

  - platform: generic
    name: disk_temps
    still_image_url: http://10.0.10.12:3000/render/d-solo/000130-PUB-falconexe/unraid-dashboard?orgId=1&refresh=1m&panelId=83&width=7000&height=500
    username: !secret grafanaUser
    password: !secret grafanaPass



sensor:
  - platform: command_line
    name: Unraid Version (Stable)
    command: /usr/bin/curl --insecure "https://s3.amazonaws.com/dnld.lime-technology.com/next/unRAIDServer.plg" 2>&1 | grep Version | awk '{print $3}' | head -n 1

  - platform: influxdb
    host: 10.0.10.5
    port: 8086
    database: home_metrics
    queries:
      - name: drive_temperatures
        value_template: '{{ value | round(0) }}'
        #group_function: last
        where: "('serial_no' != '*') and time >= now() - 12h GROUP BY time(30s), 'serial_no'"
        measurement: "'smart_device'"
        field: "last('temp_c')"

# SELECT last("temp_c") FROM "smart_device" WHERE ("serial_no" != '*') AND time >= now() - 12h GROUP BY time(30s), "serial_no"
# Could not execute query 'select mean(last('temp_c')) as value from 'smart_device' where ('serial_no' != '*') and 'time >= now() - 12h' GROUP BY time(30s), 'serial_no'' due to '400: {"error":"error parsing query: found smart_device, expected identifier at line 1, char 42"}
# Could not execute query 'select time(30s), 'serial_no'(last('temp_c')) as value from 'smart_device' where ('serial_no' != '*') and time >= now() - 12h'

# API sensors

## UnRaid Array Started Bar-Card  > 3.1.0 
  - platform: template
    sensors:
      unraid_array_status:
        friendly_name: UnRAID Array Status
        value_template: >
          {{state_attr("binary_sensor.chsunr01_server", "arrayStatus")}}

      unraid_array_status_numerical:
        friendly_name: UnRAID Array Status
        value_template: >
          {% if is_state("sensor.unraid_array_status", "Started") %}
            1
          {% else %}
            0
          {% endif %}

## UnRaid Array Protection Bar-Card  > 3.1.0 
      unraid_array_protection:
        friendly_name: UnRAID Array Protection
        value_template: >
          {{state_attr("binary_sensor.chsunr01_server", "arrayProtection")}}

      unraid_array_protection_numerical:
        friendly_name: UnRAID Array Protection
        value_template: >
          {% if is_state("sensor.unraid_array_protection", "Parity is valid.") %}
            1
          {% else %}
            0
          {% endif %}


## UnRaid Array Usage
      unraid_array_space:
        friendly_name: UnRAID Array Space
        value_template: >
          {% set state = state_attr("switch.chsunr01_array", "diskSpace") %} 
          {{ Offline if state == None else state | regex_findall_index(".*\((\d+.?\d+) %\)") | float }}
        unit_of_measurement: '%'


## HDD SNMP Temperatures

  - platform: snmp
    name: 'UnRAID PARITY Temperature'  
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    version: 2c
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.1
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: '°C'

  - platform: snmp
    name: 'UnRAID DISK1 Temperature'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    version: 2c
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.2
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: '°C'

  - platform: snmp
    name: 'UnRAID DISK2 Temperature'
    host: !secret server_ip_address_vlan20
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.3 
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: '°C'

  - platform: snmp
    name: 'UnRAID DISK3 Temperature'
    host: !secret server_ip_address_vlan20
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.4
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: '°C'

  - platform: snmp
    name: 'UnRAID DISK4 Temperature'
    host: !secret server_ip_address_vlan20
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.5
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: '°C'

  - platform: snmp
    name: 'UnRAID DISK5 Temperature'
    host: !secret server_ip_address_vlan20
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.6
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: '°C'

  - platform: snmp
    name: 'UnRAID DISK6 Temperature'
    host: !secret server_ip_address_vlan20
    port: 161
    version: 2c
    community: public
    baseoid: .1.3.6.1.4.1.8072.1.3.2.4.1.2.8.100.105.115.107.116.101.109.112.7
    accept_errors: false
    value_template: >
      {{ value.split(':')[1].strip() }}
    unit_of_measurement: '°C'

## SNMP LAN Upload

  - platform: snmp
    name: 'UnRAID LAN0 Upload (VLAN10)'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.17
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

  - platform: snmp
    name: 'UnRAID LAN1 Upload LAGG0'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.13
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

  - platform: snmp
    name: 'UnRAID LAN2 Upload LAGG0'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.14
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

  - platform: snmp
    name: 'UnRAID LAN3 Upload LAGG0'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.15
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

  - platform: snmp
    name: 'UnRAID LAN4 Upload LAGG0'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.16.16
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

## SNMP LAN Download

  - platform: snmp
    name: 'UnRAID LAN0 Download (VLAN10)'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.17
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

  - platform: snmp
    name: 'UnRAID LAN1 Download LAGG0'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.13
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

  - platform: snmp
    name: 'UnRAID LAN2 Download LAGG0'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.14
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

  - platform: snmp
    name: 'UnRAID LAN3 Download LAGG0'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.15
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}

  - platform: snmp
    name: 'UnRAID LAN4 Download LAGG0'
    host: !secret server_ip_address_vlan20
    port: 161
    community: public
    baseoid: .1.3.6.1.2.1.2.2.1.10.16
    accept_errors: false
    unit_of_measurement: "Kbps"
    value_template: >
      {{((value | float ) / 1000000 ) | round(2) }}


switch:

## WAKE ON LAN SWITCH - COMPONENT
# https://www.home-assistant.io/integrations/wake_on_lan/

  - platform: wake_on_lan
    mac: !secret server_mac_address
    name: !secret server_service_name
    host: !secret server_ip_address
    broadcast_address: !secret server_broadcast
    turn_off:
      service: switch.turn_off
      entity_id: switch.server_off

# COMMAND LINE SWITCH - COMPONENT
# https://www.home-assistant.io/integrations/switch.command_line/

  - platform: command_line
    switches:
      server_off:
        command_on: switch.home_server
        command_off: !secret server_off_cmd

