automation:
  #  Craft Room - Philips Hue Motion
  - alias: 'Craft Room lights turn-on day'
    trigger:
      platform: state
      entity_id: binary_sensor.craft_room_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.craft_room_lux
        below: '3.0'
      - condition: or
        conditions:
        - condition: state
          entity_id: !secret person_2
          state: home
        - condition: state
          entity_id: !secret person_1
          state: home
    action:
      service: light.turn_on
      data:
        entity_id: light.craft_room_shadow
        brightness: 249

  - alias: 'Craft Room lights turn-on night'
    trigger:
      platform: state
      entity_id: binary_sensor.craft_room_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.craft_room_lux
        below: '1.5'
      - condition: or
        conditions:
        - condition: state
          entity_id: !secret person_2
          state: home
        - condition: state
          entity_id: !secret person_1
          state: home
    action:
      service: light.turn_on
      data:
        entity_id: light.craft_room_shadow
        brightness: 249


  - alias: 'Craft room lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.craft_room_motion
      to: 'off'
      for:
        seconds: 50
    action:
      service: light.turn_off
      data:
        entity_id: light.craft_room_shadow
        transition: 10


# HKI Light Groups
light:
  - platform: group
    name: Craft Room
    entities:
      - light.craft_room_spot_01
      - light.craft_room_spot_02
      - light.craft_room_shadow

# Dwains Theme Light Group
group:
  craft_room_lights:
    name: Craft Room
    entities:
      - light.craft_room_spot_01
      - light.craft_room_spot_02
      - light.craft_room_shadow