sensor:
  # Agile rates
  - platform: rest
    name: Agile rates today
    resource_template: >-
      {% set region = 'A' %}
      {% set from = as_timestamp(as_timestamp(now()) | timestamp_custom('%Y-%m-%d') + 'T00:00:00') %}
      {% set to = from + 24 * 60 * 60 %}
      {% set format = '%Y-%m-%dT%H:%M:%SZ' %}
      https://api.octopus.energy/v1/products/AGILE-18-02-21/electricity-tariffs/E-1R-AGILE-18-02-21-{{ region }}/standard-unit-rates/?period_from={{ from | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) }}&period_to={{ to | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) }}
    value_template: "{{ as_timestamp(value_json.results[-1].valid_from) | timestamp_custom('%Y-%m-%d') }}"
    json_attributes:
      - "results"

  - platform: rest
    name: Agile rates tomorrow
    resource_template: >-
      {% set region = 'A' %}
      {% set from = as_timestamp(as_timestamp(now() + timedelta(days = 1)) | timestamp_custom('%Y-%m-%d') + 'T00:00:00') %}
      {% set to = from + 24 * 60 * 60 %}
      {% set format = '%Y-%m-%dT%H:%M:%SZ' %}
      https://api.octopus.energy/v1/products/AGILE-18-02-21/electricity-tariffs/E-1R-AGILE-18-02-21-{{ region }}/standard-unit-rates/?period_from={{ from | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) }}&period_to={{ to | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) }}
    value_template: "{{ as_timestamp(value_json.results[-1].valid_from) | timestamp_custom('%Y-%m-%d') }}"
    json_attributes:
      - "results"

  - platform: rest
    name: Agile rates yesterday
    resource_template: >-
      {% set region = 'A' %}
      {% set from = as_timestamp(as_timestamp(now() - timedelta(days = 1)) | timestamp_custom('%Y-%m-%d') + 'T00:00:00') %}
      {% set to = from + 24 * 60 * 60 %}
      {% set format = '%Y-%m-%dT%H:%M:%SZ' %}
      https://api.octopus.energy/v1/products/AGILE-18-02-21/electricity-tariffs/E-1R-AGILE-18-02-21-{{ region }}/standard-unit-rates/?period_from={{ from | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) }}&period_to={{ to | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) }}
    value_template: "{{ as_timestamp(value_json.results[-1].valid_from) | timestamp_custom('%Y-%m-%d') }}"
    json_attributes:
      - "results"

  - platform: template
    sensors:
      agile_upcoming_rates:
        friendly_name: Agile upcoming rates
        icon_template: mdi:flash
        value_template: "{{ states('sensor.agile_next_rate') }}"
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          results: >-
            {% set rates = (state_attr('sensor.agile_rates_today', 'results') + state_attr('sensor.agile_rates_tomorrow', 'results')) | sort(attribute='valid_from') %}
            {% set from = now().hour * 2 + (now().minute / 30) | int %}
            {% set to = from + 48 %}
            {{ rates[from:to] }}
      agile_min_upcoming_rate:
        friendly_name: Agile minimum upcoming rate
        icon_template: mdi:flash
        value_template: "{{ '%.2f' | format((state_attr('sensor.agile_upcoming_rates', 'results') | sort(attribute='value_inc_vat') | first).value_inc_vat) }}"
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          valid_from: "{{ (state_attr('sensor.agile_upcoming_rates', 'results') | sort(attribute='value_inc_vat') | first).valid_from }}"
          valid_to: "{{ (state_attr('sensor.agile_upcoming_rates', 'results') | sort(attribute='value_inc_vat') | first).valid_to }}"

      agile_avg_rate_today:
        friendly_name: Agile average rate today
        value_template: "{{ (state_attr('sensor.agile_rates_today', 'results') | sum(attribute='value_inc_vat') / 48) | round(2) }}"
        unit_of_measurement: 'p/kWh'

      agile_current_rate:
        friendly_name: Agile current rate
        icon_template: mdi:flash
        value_template: >-
          {% set from = ((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
          {{ ((state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).value_inc_vat) | round(2) }}
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          valid_from: >-
            {% set from = ((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_from }}
          valid_to: >-
            {% set from = ((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_to }}
      agile_next_rate:
        friendly_name: Agile next rate
        icon_template: mdi:flash
        value_template: >-
          {% set from = (((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) + 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
          {{ ((state_attr('sensor.agile_upcoming_rates', 'results') | selectattr('valid_from', 'eq', from) | first).value_inc_vat) | round(2) }}
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          valid_from: >-
            {% set from = (((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) + 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_upcoming_rates', 'results') | selectattr('valid_from', 'eq', from) | first).valid_from }}
          valid_to: >-
            {% set from = (((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) + 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_upcoming_rates', 'results') | selectattr('valid_from', 'eq', from) | first).valid_to }}
      agile_prev_rate:
        friendly_name: Agile previous rate
        icon_template: mdi:flash
        value_template: >-
          {% set from = (((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) - 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
          {{ ((state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).value_inc_vat) | round(2) }}
        unit_of_measurement: 'p/kWh'
        attribute_templates:
          valid_from: >-
            {% set from = (((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) - 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_from }}
          valid_to: >-
            {% set from = (((as_timestamp(utcnow()) / 1800) | round(0, 'floor') | int * 1800) - 30 * 60) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', False) %}
            {{ (state_attr('sensor.agile_rates_today', 'results') | selectattr('valid_from', 'eq', from) | first).valid_to }}

  # Consumption
  - platform: rest
    name: Electricity consumption yesterday
    resource_template: >-
      {% set mpan = '1416629951006' %}
      {% set serial = '19K0178961' %}
      {% set date = as_timestamp(now() - timedelta(days = 1)) | timestamp_custom('%Y-%m-%d') %}
      https://api.octopus.energy/v1/electricity-meter-points/{{ mpan }}/meters/{{ serial }}/consumption/?period_from={{ date + 'T00:00:00' }}&period_to={{ date + 'T23:59:59' }}
    headers:
      Authorization: !secret octopus_auth
    value_template: "{{ value_json.results | sum(attribute='consumption') | round(3) }}"
    unit_of_measurement: 'kWh'
    json_attributes:
      - "results"

  - platform: rest
    name: Gas consumption yesterday
    resource_template: >-
      {% set mprn = '4176395803' %}
      {% set serial = 'G4K00184961920' %}
      {% set date = as_timestamp(now() - timedelta(days = 1)) | timestamp_custom('%Y-%m-%d') %}
      https://api.octopus.energy/v1/gas-meter-points/{{ mprn }}/meters/{{ serial }}/consumption/?period_from={{ date + 'T00:00:00' }}&period_to={{ date + 'T23:59:59' }}
    headers:
      Authorization: !secret octopus_auth
    value_template: "{{ value_json.results | sum(attribute='consumption') | round(3) }}"
    unit_of_measurement: 'm³'
    json_attributes:
      - "results"

  - platform: template
    sensors:
      gas_cost_yesterday:
        friendly_name: Gas cost yesterday
        icon_template: mdi:cash-multiple
        value_template: >-
          {% set unit_price = 2.86 %}
          {% set standing_charge = 26.06 %}
          {% set calorific_value = 39.1 %}
          {{ ((states('sensor.gas_consumption_yesterday') | float * 1.02264 * calorific_value / 3.6) * unit_price / 100 + standing_charge / 100) | round(2) }}
        unit_of_measurement: '£'

  - platform: template
    sensors:
      electricity_cost_yesterday:
        friendly_name: Electricity cost yesterday
        icon_template: mdi:cash-multiple
        value_template: >-
          {% set standing_charge = 21 %}
          {% set rates = state_attr('sensor.agile_rates_yesterday', 'results') %}
          {% set usage = state_attr('sensor.electricity_consumption_yesterday', 'results') %}
          {% if usage | count == 48  %}
            {% set ns = namespace(total=0) %}
            {% for p in range(0, 48) %}
              {% set ns.total = ns.total + (usage[p].consumption * rates[p].value_exc_vat / 100) %}
            {% endfor %}
            {{ '%.2f' | format((ns.total + standing_charge / 100) * 1.05) }}
          {% endif %}
        unit_of_measurement: '£'
        attribute_templates:
          fixed_rate_cost: >- 
            {% set unit_price = 16.32 %}
            {% set standing_charge = 23.32 %}
            {{ ((states('sensor.electricity_consumption_yesterday') | float * unit_price / 100 + standing_charge / 100) * 1.05) | round(2) }}