# Energy Monitoring Sensros for HKI Energy Monitoring
sensor:
  - platform: mqtt
    name: "Home Instant Electricity"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'W'
    value_template: "{{ value_json['elecMtr']['0702']['04']['00']|int(base=16) }}"
    icon: 'mdi:flash'
    device_class: power

  - platform: mqtt
    name: "Home Electricity"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json['elecMtr']['0702']['00']['00']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    icon: 'mdi:flash'
    device_class: power

  - platform: mqtt
    name: "Home Daily Electricity"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json['elecMtr']['0702']['04']['01']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    icon: 'mdi:flash'
    device_class: power

  - platform: mqtt
    name: "Home Weekly Electricity"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json['elecMtr']['0702']['04']['30']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    icon: 'mdi:flash'
    device_class: power

  - platform: mqtt
    name: "Home Monthly Electricity"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json['elecMtr']['0702']['04']['40']|int(base=16) * value_json['elecMtr']['0702']['03']['01']|int(base=16) / value_json['elecMtr']['0702']['03']['02']|int(base=16) }}"
    icon: 'mdi:flash'
    device_class: power

  - platform: mqtt
    name: "Home Gas"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'm3'
    value_template: "{{ value_json['gasMtr']['0702']['00']['00']|int(base=16) * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16) }}"
    icon: 'mdi:flash'

  - platform: mqtt
    name: "Home Daily Gas"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json['gasMtr']['0702']['0C']['01']|int(base=16)  * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16) }}"
    icon: 'mdi:flash'

  - platform: mqtt
    name: "Home Weekly Gas"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json['gasMtr']['0702']['0C']['30']|int(base=16)  * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16) }}"
    icon: 'mdi:flash'

  - platform: mqtt
    name: "Home Monthly Gas"
    state_topic: "SMART/HILD/F008D1ECE298"
    unit_of_measurement: 'kWh'
    value_template: "{{ value_json['gasMtr']['0702']['0C']['40']|int(base=16)  * value_json['gasMtr']['0702']['03']['01']|int(base=16) / value_json['gasMtr']['0702']['03']['02']|int(base=16) }}"
    icon: 'mdi:flash'


#  - platform: template
#    sensors: 
#    # All monnitored devices KwH  
#      energy_total_usage:
#        friendly_name: Total Energy Usage
#        unit_of_measurement: kWh
#        value_template: >-  
#          {{ 
#            (states.sensor.bedroom_tv_smart_plug_total_daily_energy.state | float) +
#            (states.sensor.living_room_av_receiver_smart_plug_total_daily_energy.state | float) +
#            (states.sensor.office_computer_smart_plug_total_daily_energy.state | float) +
#            (states.sensor.cabinet_smart_plug_energy.state | float) +
#            (states.sensor.living_room_tv_smart_plug_total_daily_energy.state | float)
#          }}




    # All monnitored devices W
#      power_total_usage:
#        friendly_name: Total Power Usage
#        unit_of_measurement: W
#        value_template: >-  
#          {{ 
#            (states.sensor.bedroom_tv_smart_plug_wattage.state | float) +
#            (states.sensor.living_room_av_receiver_smart_plug_wattage.state | float) +
#            (states.sensor.office_computer_smart_plug_wattage.state | float) +
#            (states.sensor.cabinet_smart_plug_power.state | float) +
#            (states.sensor.living_room_tv_smart_plug_wattage.state | float)
#          }}


  - platform: template
    sensors: 

#    # Energy Cost Now
      now_energy_cost:
        unique_id: sensor.home_instant_electricity
        friendly_name: 'Now Cost'
        value_template: >-
          {% if (states.sensor.home_instant_electricity.state | float > 0) %}
            {{ ((states.sensor.home_instant_electricity.state) | float) / 1000 * (states('input_number.electricity_rate') | float ) + (states('input_number.elec_daily_service_charge') | float | round(2)) }}
          {% endif %}

    # Daily Energy Cost
      daily_energy_cost:
        unique_id: sensor.home_daily_electricity
        friendly_name: 'Daily Cost'
        value_template: >-
          {% if (states.sensor.home_daily_electricity.state | float > 0) %}
            {{ ((states.sensor.home_daily_electricity.state) | float) * (states('input_number.electricity_rate') | float ) + (states('input_number.elec_daily_service_charge') | float | round(2)) }}
          {% endif %}

    # Weekly Energy Cost
      monthly_energy_cost:
        unique_id: sensor.home_weekly_electricity
        friendly_name: 'Monthly Cost'
        value_template: >-
          {% if (states.sensor.home_weekly_electricity.state | float > 0) %}
            {{ ((states.sensor.home_weekly_electricity.state) | float) * (states('input_number.electricity_rate') | float ) + (states('input_number.elec_daily_service_charge') | float | round(2)) }}
          {% endif %}

    # Monthly Energy Cost
      monthly_energy_cost:
        unique_id: sensor.home_monthly_electricity
        friendly_name: 'Monthly Cost'
        value_template: >-
          {% if (states.sensor.home_monthly_electricity.state | float > 0) %}
            {{ ((states.sensor.home_monthly_electricity.state) | float) * (states('input_number.electricity_rate') | float ) + (states('input_number.elec_daily_service_charge') | float | round(2)) }}
          {% endif %}

#    # Gas Cost Now
      now_energy_cost:
        unique_id: sensor.home_gas
        friendly_name: 'Now Cost'
        value_template: >-
          {% if (states.sensor.home_gas.state | float > 0) %}
            {{ ((states.sensor.home_gas.state) | float) / 1000 * (states('input_number.gas_rate') | float ) + (states('input_number.gas_daily_service_charge') | float | round(2)) }}
          {% endif %}

    # Daily Gas Cost
      daily_energy_cost:
        unique_id: sensor.home_daily_gas
        friendly_name: 'Daily Cost'
        value_template: >-
          {% if (states.sensor.home_daily_gas.state | float > 0) %}
            {{ ((states.sensor.home_daily_gas.state) | float) * (states('input_number.gas_rate') | float ) + (states('input_number.gas_daily_service_charge') | float | round(2)) }}
          {% endif %}

    # Weekly Gas Cost
      monthly_energy_cost:
        unique_id: sensor.home_weekly_gas
        friendly_name: 'Monthly Cost'
        value_template: >-
          {% if (states.sensor.home_weekly_gas.state | float > 0) %}
            {{ ((states.sensor.home_weekly_gas.state) | float) * (states('input_number.gas_rate') | float ) + (states('input_number.gas_daily_service_charge') | float | round(2)) }}
          {% endif %}

    # Monthly Gas Cost
      monthly_energy_cost:
        unique_id: sensor.home_monthly_gas
        friendly_name: 'Monthly Cost'
        value_template: >-
          {% if (states.sensor.home_monthly_gas.state | float > 0) %}
            {{ ((states.sensor.home_monthly_gas.state) | float) * (states('input_number.gas_rate') | float ) + (states('input_number.gas_daily_service_charge') | float | round(2)) }}
          {% endif %}



input_number:
# Input on view for power costs per KwH
  electricity_rate:
    name: "Electricity Rate per kWh"
    min: 0.000
    max: 50.000
    mode: box
    step: 0.001
  elec_daily_service_charge:
    name: "Electricity Daily Service Charge"
    min: 0.00
    max: 50.00
    mode: box
    step: 0.01
  gas_rate:
    name: "Gas Rate per kWh"
    min: 0.000
    max: 50.000
    mode: box
    step: 0.001
  gas_daily_service_charge:
    name: "Gas Daily Service Charge"
    min: 0.00
    max: 20.00
    mode: box
    step: 0.01


group:
  smart_plugs:
    name: All Smart Plugs
    entities:
      - switch.bedroom_tv_smart_plug_relay
      - switch.living_room_av_receiver_smart_plug_relay
      - switch.office_computer_smart_plug_relay
      - switch.living_room_subwoofer_smart_socket_relay
      - switch.sp_of_cab_relay

