automation:

  #  Hall - Philips Hue Motion
  - alias: 'Hall lights turn-on'
    trigger:
      platform: state
      entity_id: binary_sensor.hall_hue_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.hall_hue_lux
        below: '1.2'
      - condition: or
        conditions:
        - condition: state
          entity_id: !secret person_2
          state: home
        - condition: state
          entity_id: !secret person_1
          state: home
    action:
      service: light.turn_on
      data:
        entity_id: light.hall
        brightness: 249

  - alias: 'Hall lights delay turn-off Rubbish collection'
    trigger:
      platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
    condition:
      - condition: time
        after: '18:30:00'
        before: '23:00:00'
        weekday:
        - wed
      - condition: state
        entity_id: binary_sensor.hall_hue_motion
        state: 'on'
      - condition: state
        entity_id: binary_sensor.garden_hue_motion
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.hall_hue_lux
        below: '1.2'
      - condition: numeric_state
        entity_id: sensor.garden_hue_lux
        below: '10'
    action:
      - service: automation.turn_off
        data:
          entity_id: automation.hall_lights_turn_off
      - delay: '00:10:00'
      - service: automation.turn_on
        data:
          entity_id: automation.hall_lights_turn_off
          

  - alias: 'Hall lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.hall_hue_motion
      to: 'off'
      for:
        seconds: 30
    action:
      service: light.turn_off
      data:
        entity_id: light.hall
        transition: 10


group:
  hall_lights:
    name: Hall Lights
    entities:
      - light.hall_spot_01
      - light.hall_spot_02

# Light Groups
light:
  - platform: group
    name: Hall
    entities:
      - light.hall_spot_01
      - light.hall_spot_02