automation:

  - alias: 'Cabinet turn-on from dimmer normal'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: cabinet_switch
        event: 1002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.cabinet_lights
          brightness: 249

  - alias: 'Cabinet increase brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: cabinet_switch
        event: 2002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.cabinet_lights
          brightness: >
            {% set bri = state_attr
            ('light.cabinet_lights', 'brightness') | int %}
            {{ [bri+30, 249] | min }}

  - alias: 'Cabinet decrease brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: cabinet_switch
        event: 3002
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.cabinet_lights
          brightness: >
            {% set bri = state_attr
            ('light.cabinet_lights', 'brightness') | int %}
            {{ [bri-30, 10] | max }}

  - alias: 'Cabinet turn-off from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: deconz_event
      event_data:
        id: cabinet_switch
        event: 4000
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.cabinet_lights

# HKI Light Group
light:
  - platform: group
    name: Cabinet Lights
    entities:
      - light.sever_cabinet_rgbw

# Dwains Theme Light Group
group:
  cabinet_lights:
    name: Cabinet Lights
    entities:
      - light.sever_cabinet_rgbw
