automation:

# Living Room - Philips Hue Dimmer
  - alias: 'Living Room turn-on from dimmer normal'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: ebff5cb60bf0093f3645102c6b769d66
        command: on_press
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.living_room_lamp_01
          brightness_pct: 50
      - service: light.turn_on
        data:
          entity_id:
            - light.living_room_shadow
          brightness_pct: 20

  - alias: 'Living Room turn-on from dimmer bright'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: ebff5cb60bf0093f3645102c6b769d66
        command: on_long_release
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.living_room
          brightness_pct: 100

  - alias: 'Living Room increase brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: ebff5cb60bf0093f3645102c6b769d66
        command: up_press
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.living_room_lamp_01
          brightness: >
            {% set bri = state_attr
            ('light.living_room_lamp_01', 'brightness') | int %}
            {{ [bri+15, 249] | min }}
      - service: light.turn_on
        data_template:
          entity_id: light.living_room_shadow
          brightness: >
            {% set bri = state_attr
            ('light.living_room_shadow', 'brightness') | int %}
            {{ [bri+5, 249] | min }}

  - alias: 'Living Room decrease brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: ebff5cb60bf0093f3645102c6b769d66
        command: down_press
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.living_room_pendant
      - service: light.turn_on
        data_template:
          entity_id: light.living_room_lamp_01
          brightness: >
            {% set bri = state_attr
            ('light.living_room_lamp_01', 'brightness') | int %}
            {{ [bri-15, 10] | max }}
      - service: light.turn_on
        data_template:
          entity_id: light.living_room_shadow
          brightness: >
            {% set bri = state_attr
            ('light.living_room_shadow', 'brightness') | int %}
            {{ [bri-15, 10] | max }}

  - alias: 'Living Room stop brightness from dimmer'
    initial_state: true
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          remote: ebff5cb60bf0093f3645102c6b769d66
          command: up_short_release
      - platform: event
        event_type: zha_event
        event_data:
          remote: ebff5cb60bf0093f3645102c6b769d66
          command: down_short_release
    action:
      - service: zha.configure
        data:
          entity: light.living_room_lamp_01
          field: "/action"
          data: {"bri_inc":0}
      - service: zha.configure
        data:
          entity: light.living_room_shadow
          field: "/action"
          data: {"bri_inc":0}

  - alias: 'Living Room turn-off from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: ebff5cb60bf0093f3645102c6b769d66
        command: off_press
    action:
      - service: light.turn_off
        entity_id:
            - light.living_room


#  Living Room - Philips Hue Motion
  - alias: 'Living Rooom lights turn-on day'
    trigger:
      platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.living_room_lux
        below: '2.5'
      - condition: or
        conditions:
        - condition: state
          entity_id: !secret person_2
          state: home
        - condition: state
          entity_id: !secret person_1
          state: home
    action:
      service: light.turn_on
      data:
        brightness: 51
        rgb_color: [134, 17, 255]
        entity_id: 
          - light.living_room_shadow


  - alias: 'Living Rooom lights turn-on night'
    trigger:
      platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.living_room_lux
        below: '1.1'
      - condition: state
        entity_id: media_player.living_room_nvidia_shield_adb
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: !secret person_2
          state: home
        - condition: state
          entity_id: !secret person_1
          state: home
    action:
      service: scene.turn_on
      data:
        entity_id: scene.living_room_lamps_bright


  - alias: 'Living Rooom lights delay turn-off on deconz event'
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: ebff5cb60bf0093f3645102c6b769d66
        event: 1002
    action:
      - service: automation.turn_off
        data:
          entity_id: automation.living_room_lights_turn_off
      - delay: '04:30:00'
      - service: automation.turn_on
        data:
          entity_id: automation.living_room_lights_turn_off


  - alias: 'Living Rooom lights enable turn-off on deconz event'
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: ebff5cb60bf0093f3645102c6b769d66
        event: 4000
    action:
      - service: automation.turn_on
        data:
          entity_id: automation.living_room_lights_turn_off


  - alias: 'Living Room lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'off'
      for:
        minutes: 10
    condition:
      - condition: state
        entity_id: media_player.living_room_nvidia_shield_adb
        state: 'off'
    action:
      service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 10
