automation:

#  Office - Philips Hue Motion
  - alias: 'Office lights turn-on'
    trigger:
      platform: state
      entity_id: binary_sensor.office_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.office_lux
        below: '1.2'
      - condition: or
        conditions:
        - condition: state
          entity_id: !secret person_2
          state: 'home'
        - condition: state
          entity_id: !secret person_1
          state: 'home'
    action:
      service: light.turn_on
      data:
        entity_id: light.office
        brightness: 249

  - alias: 'Office lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.office_motion
      to: 'off'
      for:
        minutes: 30
    condition:
      - condition: state
        entity_id: device_tracker.chsdt01
        state: 'not_home'
    action:
      service: light.turn_off
      data:
        entity_id: light.office
        transition: 10


  - alias: 'Tag office_desk is scanned'
    trigger:
      platform: tag
      tag_id: d08086f0-835d-48ce-ae5e-047db07a9572
    condition: []
    action:
      service: light.toggle
      data: 
        entity_id: light.office
        brightness: 249
      #mode: single

  - alias: 'Notify when office lights turned on or off'
    trigger:
      platform: state
      entity_id: light.office
    condition: []
    action:
      service: notify.discord
      data: 
        message: Someone just turned {{states ('light.office') }} the Office Lights
        target:
          - !secret ha_channel

#  Office - Philips Hue Dimmer

  - alias: 'Office turn-on from dimmer normal'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 421148d1751cc5c9068ede5c43c3cb23
        command: on_press
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.office
          brightness_pct: 50


  - alias: 'Office turn-on from dimmer bright'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 421148d1751cc5c9068ede5c43c3cb23
        command: on_long_release
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.office
          brightness_pct: 100

  - alias: 'Office increase brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 421148d1751cc5c9068ede5c43c3cb23
        command: up_press
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.office
          brightness: >
            {% set bri = state_attr
            ('light.office', 'brightness') | int %}
            {{ [bri+15, 249] | min }}

  - alias: 'Office decrease brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 421148d1751cc5c9068ede5c43c3cb23
        command: down_press
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.office
          brightness: >
            {% set bri = state_attr
            ('light.office', 'brightness') | int %}
            {{ [bri-15, 10] | max }}

  - alias: 'Office stop brightness from dimmer'
    initial_state: true
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          remote: 421148d1751cc5c9068ede5c43c3cb23
          command: up_short_release
      - platform: event
        event_type: zha_event
        event_data:
          remote: 421148d1751cc5c9068ede5c43c3cb23
          command: down_short_release
    action:
      - service: deconz.configure
        data:
          entity: light.office
          field: "/action"
          data: {"bri_inc":0}

  - alias: 'Office turn-off from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 421148d1751cc5c9068ede5c43c3cb23
        command: off_press
    action:
      - service: light.turn_off
        entity_id:
            - light.office
