automation:

  # Bedroom - Philips Hue Dimmer
  - alias: 'Bedroom turn-on from dimmer normal'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 9e5d0c68936c2d1b1edc7b37c92d69d9
        command: on_press
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.bedroom_lamp_01
          brightness_pct: 50

  - alias: 'Bedroom turn-on from dimmer bright'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 9e5d0c68936c2d1b1edc7b37c92d69d9
        command: on_long_release
    action:
      - service: light.turn_on
        data:
          entity_id:
            - light.bedroom
          brightness_pct: 100

  - alias: 'Bedroom increase brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 9e5d0c68936c2d1b1edc7b37c92d69d9
        command: up_press
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamp_01
          brightness: >
            {% set bri = state_attr
            ('light.bedroom_lamp_01', 'brightness') | int %}
            {{ [bri+15, 249] | min }}

  - alias: 'Bedroom decrease brightness from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 9e5d0c68936c2d1b1edc7b37c92d69d9
        command: down_press
    action:
      - service: light.turn_off
        data_template:
          entity_id: light.bedroom_pendants
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom_lamp_01
          brightness: >
            {% set bri = state_attr
            ('light.bedroom_lamp_01', 'brightness') | int %}
            {{ [bri-15, 10] | max }}

  - alias: 'Bedroom stop brightness from dimmer'
    initial_state: true
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          remote: 9e5d0c68936c2d1b1edc7b37c92d69d9
          command: up_short_release
      - platform: event
        event_type: zha_event
        event_data:
          remote: 9e5d0c68936c2d1b1edc7b37c92d69d9
          command: down_short_release
    action:
      - service: deconz.configure
        data:
          entity: light.bedroom_lamp_01
          field: "/action"
          data: {"bri_inc":0}

  - alias: 'Bedroom turn-off from dimmer'
    initial_state: true
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 9e5d0c68936c2d1b1edc7b37c92d69d9
        command: off_press
    action:
      - service: light.turn_off
        entity_id:
            - light.bedroom
