automation:

#  Office - Philips Hue Motion
  - alias: 'Office lights turn-on'
    trigger:
      platform: state
      entity_id: binary_sensor.office_motion
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.office_lux
        below: '1.2'
      - condition: or
        conditions:
        - condition: state
          entity_id: !secret person_2
          state: 'home'
        - condition: state
          entity_id: !secret person_1
          state: 'home'
    action:
      service: light.turn_on
      data:
        entity_id: light.office
        brightness: 249

  - alias: 'Office lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.office_motion
      to: 'off'
      for:
        minutes: 30
    condition:
      - condition: state
        entity_id: device_tracker.chsdt01
        state: 'not_home'
    action:
      service: light.turn_off
      data:
        entity_id: light.office
        transition: 10


  - alias: 'Tag office_desk is scanned'
    trigger:
      platform: tag
      tag_id: d08086f0-835d-48ce-ae5e-047db07a9572
    condition: []
    action:
      service: light.toggle
      data: 
        entity_id: light.office
        brightness: 249
      #mode: single

  - alias: 'Notify when office lights turned on or off'
    trigger:
      platform: state
      entity_id: light.office
    condition: []
    action:
      service: notify.discord
      data: 
        message: Someone just turned {{states ('light.office') }} the Office Lights
        target:
          - !secret ha_channel


group:
  office_lights:
    name: Office Lights
    entities:
      - light.office_spot_01
      - light.office_spot_02
      - light.office_wled

# Light Groups
light:
  - platform: group
    name: Office
    entities:
      - light.office_spot_01
      - light.office_spot_02
      - light.office_wled