# Hue Remote Automations

### Turn on Actions
- alias: Turn on Christmas Lights
  trigger:
    platform: state
    entity_id:  sensor.living_room_switch
    to: '1_click_up'
  action:
    service: homeassistant.turn_on
    entity_id: switch.christmas_lights

- alias: Turn on Lamp
  trigger:
    platform: state
    entity_id:  sensor.living_room_switch
    to: '1_click'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Lamp Morning"

- alias: Turn on Pendant
  trigger:
    platform: state
    entity_id:  sensor.living_room_switch
    to: '1_hold'
  action:
    service: hue.hue_activate_scene
    data:
      group_name: "Living Room"
      scene_name: "Pendant"

#- alias: Lamp Dimmer
#  trigger:
#    - platform: state
#      entity_id: sensor.living_room_switch
#      to: '2_click_up'
#    - platform: state
#      entity_id: input_number.livingroom_brightness
#  condition:
#    condition: and
#    conditions:
#    - condition: state
#      entity_id: light.living_room_lamp
#      state: 'on'
#    - condition: state
#      entity_id: light.living_room_pendant
#      state: 'off'
#  action:
#    service: light.turn_on
#    data_template:
#      entity_id: light.living_room_lamp
#      brightness: "{{ states('input_number.livingroom_brightness') | int }}"

### Turn off Actions
- alias: Turn off Pendant
  trigger:
    platform: state
    entity_id:  sensor.living_room_switch
    to: '4_click_up'
  action:
    service: light.turn_off
    entity_id: light.living_room_pendant

- alias: Turn off Lamp
  trigger:
    platform: state
    entity_id:  sensor.living_room_switch
    to: '4_click_up'
  action:
    service: light.turn_off
    entity_id: light.living_room_lamp

- alias: Turn off Christmas Lights
  trigger:
    platform: state
    entity_id:  sensor.living_room_switch
    to: '4_click_up'
  action:
    service: homeassistant.turn_off
    entity_id: switch.christmas_lights