sensor:

## Min/max Sensor
# https://www.home-assistant.io/integrations/min_max/

# Downstairs Average Temperature

  - platform: min_max
    type: mean
    name: downstairs_average_temp
    entity_ids:
      - sensor.kitchen_temperature
      - sensor.living_room_temperature
      - sensor.living_room_thermostat_temperature
      - sensor.bedroom_temperature
      - sensor.hall_temperature

# Upstairs Average Temperature
  - platform: min_max
    type: mean
    name: upstairs_average_temp
    entity_ids:
      - sensor.landing_temperature
      - sensor.office_temperature
      - sensor.bedroom_temperature
      - sensor.craft_room_temperature
      - sensor.stairs_temperature

# Home Average Temperature
  - platform: min_max
    type: mean
    name: Home Average Temp
    entity_ids:
        - sensor.kitchen_temperature
        - sensor.living_room_temperature
        - sensor.living_room_thermostat_temperature
        - sensor.bathroom_temperature
        - sensor.hall_temperature
        - sensor.landing_temperature
        - sensor.stairs_temperature
        - sensor.office_temperature
        - sensor.bedroom_temperature
        - sensor.craft_room_temperature
