automation:

#  Landing - Philips Hue Motion
  - alias: 'Landing lights turn-on'
    trigger:
      platform: state
      entity_id: binary_sensor.landing_occupancy
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.landing_illuminance
          below: '2'
        - condition: time
          before: '23:00:00'
          after: '17:00:00'
        - condition: or
          conditions:
            - condition: state
              entity_id: !secret person_2
              state: home
            - condition: state
              entity_id: !secret person_1
              state: home       
    action:
      service: light.turn_on
      data:
        entity_id: light.landing_spot_01
        brightness: 150

  #  Stairs - Philips Hue Motion
  - alias: 'Stairs lights turn-on'
    trigger:
      platform: state
      entity_id: binary_sensor.stairs_occupancy
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.stairs_illuminance
        below: '2'
      - condition: or
        conditions:
        - condition: state
          entity_id: !secret person_2
          state: home
        - condition: state
          entity_id: !secret person_1
          state: home
    action:
      service: light.turn_on
      data:
        entity_id: light.stairs_spot_01
        brightness: 150


  - alias: 'Landing lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.landing_occupancy
      to: 'off'
      for:
        seconds: 30
    action:
      service: light.turn_off
      data:
        entity_id: light.landing_spot_01
        transition: 10

  - alias: 'Stairs lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.stairs_occupancy
      to: 'off'
      for:
        seconds: 30
    action:
      service: light.turn_off
      data:
        entity_id: light.stairs_spot_01
        transition: 10

  #  Loft - Contact Sensor Open
  - alias: 'Loft lights turn-on'
    trigger:
      platform: state
      entity_id: binary_sensor.loft_hatch
      to: 'on'
    action:
      service: light.turn_on
      data:
        entity_id: light.loft_pendant_01
        brightness: 254

  #  Loft - Contact Sensor Closed
  - alias: 'Loft lights turn-off'
    trigger:
      platform: state
      entity_id: binary_sensor.loft_hatch
      to: 'off'
    action:
      service: light.turn_off
      data:
        entity_id: light.loft_pendant_01
