---
## RESTful Sensor
# https://www.home-assistant.io/integrations/rest/

# HASSIO Version

- platform: rest
  resource: https://s3.amazonaws.com/hassio-version/stable.json
  name: Latest HA Version
  value_template: "{{ value_json.homeassistant.default }}"
  scan_interval: 3600
